### ISSUE TITLE
EDMCLogging: Handle where logging goes through a class-level property.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1044]
```
Traceback (most recent call last):
  File "plug.pyc", line 270, in notify_journal_entry
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\load.py", line 214, in journal_entry
    return journal_entry_wrapper(cmdr, is_beta, system, this.SysFactionState, this.SysFactionAllegiance,
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\load.py", line 234, in journal_entry_wrapper
    clientreport.submit(cmdr, is_beta, client, entry)
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\clientreport.py", line 60, in submit
    clientReport(cmdr, is_beta, client).start()
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\clientreport.py", line 25, in __init__
    Emitter.__init__(self, cmdr, is_beta, None, None, None,
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\emitter.py", line 64, in __init__
    Emitter.setRoute(is_beta, client)
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\emitter.py", line 78, in setRoute
    Debug.logger.debug("Release not in github")
  File "logging\__init__.pyc", line 1434, in debug
  File "logging\__init__.pyc", line 1589, in _log
  File "logging\__init__.pyc", line 1598, in handle
  File "logging\__init__.pyc", line 806, in filter
  File "EDMCLogging.pyc", line 266, in filter
  File "EDMCLogging.pyc", line 360, in caller_attributes
AttributeError: 'classmethod' object has no attribute '__qualname__'
```
https://github.com/canonn-science/EDMC-Canonn/tree/edmc-upgrdae

**Comment by Athanasius** [comment]
This has been resolved in `develop`.
