### ISSUE TITLE
Possible `EngineerProgress` issue with missing `Engineer` key/value

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1078]
```python
2021-05-19 19:56:52.491 - DEBUG - 15828:10080:10080 monitor.EDLogs.parse_entry:1513: Invalid journal entry:
b'{ "timestamp":"2021-05-19T18:56:08Z", "event":"EngineerProgress", "Engineers":[ { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Invited" }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Known" }, { "Progress":"Unlocked", "RankProgress":3, "Rank":3 }, { "Progress":"Known" }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Invited" }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":8, "Rank":2 }, { "Progress":"Unlocked", "RankProgress":72, "Rank":3 }, { "Progress":"Unlocked", "RankProgress":41, "Rank":3 }, { "Progress":"Unlocked", "RankProgress":77, "Rank":2 }, { "Progress":"Known" }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":34, "Rank":4 }, { "Progress":"Invited" }, { "Progress":"Invited" }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":1 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Unlocked", "RankProgress":0, "Rank":5 }, { "Progress":"Known" }, { "Progress":"Invited" } ] }\r\n'
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 767, in parse_entry
    self.state['Engineers'] = {
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 768, in <dictcomp>
    e['Engineer']: ((e['Rank'], e.get('RankProgress', 0)) if 'Rank' in e else e['Progress'])
KeyError: 'Engineer'
```

This is in live Odyssey, simply logging in.  I'm in my Fleet Carrier (in my Python).

**Comment by Athanasius** [comment]
This *might* have been due to server issues.  We still need to ensure we won't then send bad data to Inara.

**Comment by Athanasius** [comment]
We would have sent the `EngineerProgress` event as-is to EDSM:

> Anthor (EDSM/SCIM): I think it check for engineer before doing anything
> Anthor (EDSM/SCIM): https://github.com/EDSM-NET/Journal-Events/blob/master/Event/EngineerProgress.php

So no direct effect on places we send the data.  Of course EDMC plugins might be relying on it and fooled into thinking the Cmdr has no progress, but there's nothing we can do about that.

**Comment by Athanasius** [comment]
With the extra validation in https://github.com/EDCD/EDMarketConnector/pull/1084 I believe we're now in the clear.

If that validation doesn't pass then we won't set/change `monitor.state['Engineers']` and it *should* be its default empty `dict` *or* what a previous same-EDMC-session different-game-session caused us to set, and/or what a 'progress' version of the event updated it to be.

So, no data, don't send, should be good.

**Comment by Athanasius** [comment]
Ah, wait, we will still send the raw event to EDSM, but then it gets to deal with it.
