### ISSUE TITLE
`EngineerProgress` has 'bare' engineer if it's the only one.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1111]
Reported by `@a31` on Discord:

```python
2021-05-25 17:11:50.657 - DEBUG - 84132:85200:85200 monitor.EDLogs.parse_entry:1581: Invalid journal entry:
b'{ "timestamp":"2021-05-24T17:57:52Z", "event":"EngineerProgress", "Engineer":"Felicity Farseer", "EngineerID":300100, "Progress":"Invited" }\r\n'
Traceback (most recent call last):
  File "monitor.pyc", line 769, in parse_entry
  File "monitor.pyc", line 1690, in event_valid_engineerprogress
KeyError: 'Engineers'
```

**Comment by Athanasius** [comment]
Fix merged into `develop`
