### ISSUE TITLE
Getting exeptions from edms plugin

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1251]
**Please complete the following information:**
 - Version: `commit e6c6f7f1554b46bc86ffdf754d19a236b76c482a (HEAD, refs/remotes/origin-fork-norohind/enhancement/1096/CAPI-pretend-down-CL-arg, refs/heads/enhancement/1096/CAPI-pretend-down-CL-arg)`
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian

[5.1.4_beta0_00.log](https://github.com/EDCD/EDMarketConnector/files/6997779/5.1.4_beta0_00.log)
[EDMarketConnector-debug-5.1.4_beta0_00.log](https://github.com/EDCD/EDMarketConnector/files/6997780/EDMarketConnector-debug-5.1.4_beta0_00.log)

**Describe the bug**
edsm.py core plugin throwing such exceptions:
```
2021-08-17 09:50:19.933 - DEBUG - 218284:216380:216380 plugins.edsm.worker:753: Attempt to send API events: retrying == 0
Traceback (most recent call last):
  File "F:\ftpRoot\ED\EDMarketConnector\plugins\edsm.py", line 703, in worker
    'journal.locations', f'Overall POST data (elided) is:\n{json.dumps(data_elided, indent=2)}'
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Computer\AppData\Local\Programs\Python\Python39-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**To Reproduce**
1. Manage to trigger edsm plugin to send any event to edsm
2. Check your logs
3. See exceptions

**Expected behavior**
No exceptions

**Screenshots**
Screenshot where we can see another indication of edsm plugin's error in the bottom of main UI
![image](https://user-images.githubusercontent.com/60548839/129679937-f019a79a-6496-4c12-8d48-55b49ab6356b.png)

**Additional context**
I think it's happening because in [this](https://github.com/EDCD/EDMarketConnector/blob/develop/plugins/edsm.py#L703) trace_if trying to json.dumps `data_elided` which, for some reason, is bytes, not dict.

**Comment by norohind** [comment]
Well, actually, it's because `data_elided['message']` is bytes, not whole `data_elided`.
