### ISSUE TITLE
Log message trows exception: Formatting field not found in record: 'osthreadid'

### ISSUE THREAD

**Issue by chr7** [EDCD/EDMarketConnector#1357]
- Version: 5.2.2
 - Game Version: Horizon
 - OS: Ubuntu 20.04.3 LTS
 - OS Locale: de_de
 - If applicable: Firefox

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 440, in format
    return self._format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 436, in _format
    return self._fmt % record.__dict__
KeyError: 'osthreadid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 671, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 640, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 442, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'osthreadid'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "EDMarketConnector.py", line 1997, in <module>
    app = AppWindow(root)
  File "EDMarketConnector.py", line 457, in __init__
    plug.load_plugins(master)
  File "/home/ch/Programs/EDMarketConnector/plug.py", line 157, in load_plugins
    found.append(Plugin(name, os.path.join(config.plugin_dir_path, name, 'load.py'), plugin_logger))
  File "/home/ch/Programs/EDMarketConnector/plug.py", line 53, in __init__
    newname = module.plugin_start3(os.path.dirname(loadfile))
  File "/home/ch/.local/share/EDMarketConnector/plugins/click_counter/load.py", line 112, in plugin_start3
    logger.info(f"{PLUGIN_NAME} has been loaded")
Message: 'ClickCounter has been loaded'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 440, in format
    return self._format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 436, in _format
    return self._fmt % record.__dict__
KeyError: 'osthreadid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.8/logging/handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 671, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 640, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 442, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'osthreadid'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/ch/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "EDMarketConnector.py", line 1997, in <module>
    app = AppWindow(root)
  File "EDMarketConnector.py", line 457, in __init__
    plug.load_plugins(master)
  File "/home/ch/Programs/EDMarketConnector/plug.py", line 157, in load_plugins
    found.append(Plugin(name, os.path.join(config.plugin_dir_path, name, 'load.py'), plugin_logger))
  File "/home/ch/Programs/EDMarketConnector/plug.py", line 53, in __init__
    newname = module.plugin_start3(os.path.dirname(loadfile))
  File "/home/ch/.local/share/EDMarketConnector/plugins/click_counterEDMC-SystemScan/load.py", line 112, in plugin_start3
    logger.info(f"{PLUGIN_NAME} has been loaded")
Message: 'ClickCounter has been loaded'
Arguments: ()
```

**Describe the bug**
Copied the click_counter example (docs/examples/click_counter/) into the sub-folder of the plugin. The following line of the code throws the exception: `logger.info("ClickCounter instantiated")`

**To Reproduce**
1. Copy the folder 'click_counter' in the plugin sub-folder.
2. Start EDMarketConnector
3. Log error message is thrown

**Expected behavior**
No log message error

**Additional context**
I though to use the click_counter file as a base to start my own plugin.

**Comment by Athanasius** [comment]
All that `python3.8/` in your log output says you're trying to use Python 3.8.  We only test against 3.9 (currently 3.9.9) now.

**Comment by Athanasius** [comment]
Having said that, the `threading.get_native_id()` that we rely upon to fill in `osthreadid` was added in Python 3.8.  So we need to see your *entire* log file in order to see why that didn't work.  What we need is the entire stdout/stderr output of the program:

```
python EDMarketConnector.py 2>&1 | tee -a edmc.log.txt
```
and drag the resulting file into a comment here.

**Comment by chr7** [comment]
I see but:
1. I just copied `click_counter/load.py`
2. `logger.info("ClickCounter instantiated")` is not a very specific feature that is not supposed to work
3. Strangely enough, similar log calls work in other plugins without a problem thus I suspect something specific with `click_counter` (e.g. missing initialization etc.)

I run EDMarketConnector again and attached the complete log file now.

**Comment by chr7** [comment]
[edmc.log.txt](https://github.com/EDCD/EDMarketConnector/files/7577004/edmc.log.txt)

**Comment by Athanasius** [comment]
> I see but:
> 
>     1. I just copied `click_counter/load.py`
> 
>     2. `logger.info("ClickCounter instantiated")` is not a very specific feature that is not supposed to work
> 
>     3. Strangely enough, similar log calls work in other plugins without a problem thus I suspect something specific with `click_counter` (e.g. missing initialization etc.)
> 
> 
> I run EDMarketConnector again and attached the complete log file now.

Yes, the folder is called `click_counter`, but the PLUGIN_NAME used in requesting a logger is `ClickCounter`, which means it uses a fresh logger that doesn't have our custom fields available.  Pinging @A-UNDERSCORE-D to fix this.

If you're trying to write a plugin then please consult https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md

**Comment by chr7** [comment]
oh ... in that case I suggest to change the line `PLUGIN_NAME = "ClickCounter"` to `PLUGIN_NAME = os.path.basename(os.path.dirname(__file__))` (and add `import os` at the top). That would avoid this pitfall and make it easier for beginners.

**Comment by Athanasius** [comment]
Fixed in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.2.3
