### ISSUE TITLE
Store and retry **CAPI**-based EDDN messages

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1463]
Currently it's only `export_journal_entry()` that is storing messages in the replaylog so that they can be retried if they fail.  The path from `cmdr_data()` -> `export_commodites()` (and the others) -> `send()` needs to also do this.

I'm trying to track down why I was getting:

2022-02-13 18:33:12.482 UTC - DEBUG - 28488:27880:27880 plugins.eddn.cmdr_data:1666: Failed exporting data
Traceback (most recent call last):
  File "urllib3\connectionpool.pyc", line 703, in urlopen
  File "urllib3\connectionpool.pyc", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.pyc", line 444, in _make_request
  File "http\client.pyc", line 1374, in getresponse
  File "http\client.pyc", line 318, in begin
  File "http\client.pyc", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.pyc", line 440, in send
  File "urllib3\connectionpool.pyc", line 785, in urlopen
  File "urllib3\util\retry.pyc", line 550, in increment
  File "urllib3\packages\six.pyc", line 769, in reraise
  File "urllib3\connectionpool.pyc", line 703, in urlopen
  File "urllib3\connectionpool.pyc", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.pyc", line 444, in _make_request
  File "http\client.pyc", line 1374, in getresponse
  File "http\client.pyc", line 318, in begin
  File "http\client.pyc", line 287, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 1658, in cmdr_data
    this.eddn.export_commodities(data, is_beta)
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 483, in export_commodities
    self.send(data['commander']['name'], {
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 257, in send
    r = self.session.post(self.eddn_url, data=encoded, timeout=self.TIMEOUT, headers=headers)
  File "requests\sessions.pyc", line 577, in post
  File "requests\sessions.pyc", line 529, in request
  File "requests\sessions.pyc", line 645, in send
  File "requests\adapters.pyc", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
a few times today.  Nothing relevant on the EDDN server, which is just weird.  If EDMC code hit its timeout than the error should say *that*, not this "Remote end closed connection without response".

**Comment by Rixxan** [comment]
Given that this is over 3 years old, and isn't being widely reported, I'm going to close this out. (If someone replicates, please reopen).
