### ISSUE TITLE
Prevent plugins' widgets from causing core code/UI issues

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1479]
When we released 5.3.0 it was found that the [Hutton Helper](https://github.com/aarronc/hutton-helper) plugin, if you were using Transparent theme, would cause:

1. Clicking 'OK' on 'Settings' after switching to Transparent theme doesn't close the Settings dialogue
2. If you already had Transparent theme selected, then **NO EDMC UI** would appear on startup.

Obviously we should add some try/except in key places to prevent this.

For case 1:

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\prefs.py", line 1266, in apply
    theme.apply(self.parent)
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\theme.py", line 326, in apply
    self._update_widget(widget)
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\theme.py", line 307, in _update_widget
    widget.configure(font=self.current['font'])
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\Hutton-Helper\widgets.py", line 84, in configure
    if 'font' in kwargs:  # capture full font details
AttributeError: module 'collections' has no attribute 'Iterable'
```

That's in `theme.py:_Theme._update_widget()` where it's walking through all the widgets.

NB: This doesn't happen *every* time, which is weird.

**Comment by Athanasius** [comment]
Ah, it not triggering was likely due to the plugin having an auto updater that had brought in fixed code.

OK, PR coming up with a try/except that *might* still leave things in a broken state theme-wise, but at least the UI is still working when it hits this.

**Comment by Athanasius** [comment]
Closing as this was long since merged.
