### ISSUE TITLE
"Running from source" wiki page is misleading with final dots after "pip install"

### ISSUE THREAD

**Issue by tommyblue** [EDCD/EDMarketConnector#1498]
**Describe the bug**

At https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#use-pip-to-install-application-requirements some `pip` related code examples are misleading because they end with a dot. Copying that dot and trying to run the command with it creates odd behaviour.

For example, running:
`pip install -r requirements.txt .`

fails with:

```
  ERROR: Command errored out with exit status 1:
   command: EDMarketConnector/venv/bin/python EDMarketConnector/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpw2niv4c4
       cwd: /tmp/pip-req-build-9qf9d7s2
  Complete output (18 lines):
  Traceback (most recent call last):
    File "EDMarketConnector/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "EDMarketConnector/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "EDMarketConnector/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ibwt2ytb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-ibwt2ytb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ibwt2ytb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-ibwt2ytb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 22, in <module>
      from lxml import etree
  ModuleNotFoundError: No module named 'lxml'
  ----------------------------------------
```

**To Reproduce**
1. Go to https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source
2. Follow the instructions but mistakenly include the final dot in the `pip install` commands

**Comment by Athanasius** [comment]
Silly me, assuming the formatting made it obvious that the `.` was outside the `pre-formatted text`.

Anyway, changed.

**Comment by tommyblue** [comment]
thank you @Athanasius 
yes the formatting made it clear, but I mistakenly copied the line to the end, also including the dot but it took some time to understand that the error was caused by that
