### ISSUE TITLE
EDMC is unable to read my journal files

### ISSUE THREAD

**Issue by kadiron** [EDCD/EDMarketConnector#2265]
- Version: 5.11.2+87f59a5
 - Game Version: Odyssey
 - OS: Windows 11 (had the same behavior with Windows 10)
 - OS Locale: US

The Market Connector is unable to read my journal files, I'm just seeing "Error: Check E:D journal file location". Might have something to do with my PC being a domain member and my user using a roaming profile, so my user home resides on a network share of an windows file server.
I think the most relevant line in the debug log ist "OSError: [WinError 4350] This file is currently not available for use on this computer: '\\\\HOSTNAME\\Users$\\USERNAME\\Saved Games\\Frontier Developments\\Elite Dangerous\\Journal.2022-09-09T182727.01.log'"
The journal file location is correct, EDMC is obviously finding the current game log file and I have no issues with running EDDiscovery.

%temp%\edmarketconnector.log:
2024-06-23 11:48:55.795 UTC - DEBUG - 24992:38316:38316 companion.Session.__init__:644: Starting CAPI queries thread...
2024-06-23 11:48:55.800 UTC - DEBUG - 24992:18912:18912 companion.Session.capi_query_worker:781: CAPI worker thread starting
2024-06-23 11:48:55.800 UTC - DEBUG - 24992:38316:38316 companion.Session.__init__:651: Done
2024-06-23 11:48:55.817 UTC - INFO - 24992:38316:38316 EDMarketConnector.__main__:2079: Startup v5.11.2+87f59a5 : Running on Python v3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)]
2024-06-23 11:48:55.821 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.__main__:2080: Platform: win32 sys.getwindowsversion(major=10, minor=0, build=22631, platform=2, service_pack='')
argv[0]: EDMarketConnector.exe
exec_prefix: C:\Program Files (x86)\EDMarketConnector
executable: C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe
sys.path: ['C:\\Program Files (x86)\\EDMarketConnector\\library.zip']
2024-06-23 11:48:55.822 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: Initial Locale
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.822 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: After LC_ALL defaults set
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.823 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.__main__:2120: Locale LC_CTYPE: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.837 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: After switching to UTF-8 encoding (same language)
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
E:D Market Connector 5.11.2+87f59a5
2024-06-23 11:48:55.838 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.setup_killswitches:1988: fetching killswitches...
2024-06-23 11:48:55.839 UTC - INFO - 24992:38316:38316 killswitch.fetch_kill_switches:346: Attempting to fetch kill switches
2024-06-23 11:48:55.895 UTC - INFO - 24992:38316:38316 killswitch.parse_kill_switches:419: Kill switches last updated 18 October 2021
2024-06-23 11:48:55.896 UTC - TRACE - 24992:38316:38316 EDMCLogging.setup_main_list:90: 0 Active Killswitches:
2024-06-23 11:48:55.952 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "coriolis" from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
2024-06-23 11:48:55.957 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "eddn" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
2024-06-23 11:48:55.973 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "edsm" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
2024-06-23 11:48:55.981 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_start3:231: Starting worker thread...
2024-06-23 11:48:55.982 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:828: Starting...
2024-06-23 11:48:55.982 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_start3:235: Done.
2024-06-23 11:48:55.985 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2024-06-23 11:48:55.986 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2024-06-23 11:48:55.997 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_start3:206: Starting worker thread...
2024-06-23 11:48:55.999 UTC - DEBUG - 24992:39508:39508 plugins.inara.new_worker:1538: Starting...
2024-06-23 11:48:55.999 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_start3:210: Done.
2024-06-23 11:48:55.999 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "spansh_core" from "C:\Program Files (x86)\EDMarketConnector\plugins\spansh_core.py"
2024-06-23 11:48:56.016 UTC - INFO - 24992:38316:38316 plugins.eddn.EDDNSender.sqlite_queue_v1:211: New 'eddn_queue-v1.db' created
2024-06-23 11:48:56.093 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.start:198: Begin...
2024-06-23 11:48:56.175 UTC - DEBUG - 24992:24496:24496 plugins.edsm.process_discarded_events:749: Got "events to discard" list, commencing queue consumption...
2024-06-23 11:49:00.767 UTC - ERROR - 24992:38316:38316 monitor.EDLogs.start:224: Failed to find latest logfile
Traceback (most recent call last):
  File "monitor.pyc", line 221, in start
  File "monitor.pyc", line 282, in journal_newest_filename
  File "<frozen genericpath>", line 65, in getctime
OSError: [WinError 4350] This file is currently not available for use on this computer: '\\\\HOSTNAME\\Users$\\USERNAME\\Saved Games\\Frontier Developments\\Elite Dangerous\\Journal.2022-09-09T182727.01.log'
2024-06-23 11:49:00.822 UTC - INFO - 24992:38316:38316 update.check_for_fdev_updates:71: FDEV ID file commodity.csv already up to date.
2024-06-23 11:49:00.874 UTC - INFO - 24992:38316:38316 update.check_for_fdev_updates:71: FDEV ID file rare_commodity.csv already up to date.
2024-06-23 11:49:04.104 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1873: Starting shutdown procedures...
2024-06-23 11:49:04.105 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1876: Closing update checker...
2024-06-23 11:49:04.106 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1883: Notifying plugins to stop...
2024-06-23 11:49:04.107 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "EDDN" to stop...
2024-06-23 11:49:04.107 UTC - DEBUG - 24992:38316:38316 plugins.eddn.plugin_stop:2248: Calling this.eddn.close()
2024-06-23 11:49:04.108 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDN.close:605: Closing Sender...
2024-06-23 11:49:04.108 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:243: Closing db cursor.
2024-06-23 11:49:04.109 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:247: Closing db connection.
2024-06-23 11:49:04.109 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:251: Closing EDDN requests.Session.
2024-06-23 11:49:04.110 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDN.close:609: Done.
2024-06-23 11:49:04.110 UTC - DEBUG - 24992:38316:38316 plugins.eddn.plugin_stop:2250: Done.
2024-06-23 11:49:04.110 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "EDSM" to stop...
2024-06-23 11:49:04.111 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_stop:260: Signalling queue to close...
2024-06-23 11:49:04.111 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:848: Empty queue message, setting closing = True
2024-06-23 11:49:04.112 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:966: closing, so returning.
2024-06-23 11:49:04.113 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_stop:269: Done.
2024-06-23 11:49:04.113 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "Inara" to stop...
2024-06-23 11:49:04.114 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_stop:226: We have no way to ask new_worker to stop, but...
2024-06-23 11:49:04.114 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_stop:233: Done.
2024-06-23 11:49:04.114 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "Spansh" to stop...
2024-06-23 11:49:04.115 UTC - INFO - 24992:38316:38316 plug.notify_stop:269: Done
2024-06-23 11:49:04.115 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1888: Unregistering hotkey manager...
2024-06-23 11:49:04.116 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:205: No thread
2024-06-23 11:49:04.116 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:207: Done.
2024-06-23 11:49:04.117 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1892: Closing CAPI query thread...
2024-06-23 11:49:04.118 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1896: Closing dashboard...
2024-06-23 11:49:04.119 UTC - INFO - 24992:18912:18912 companion.Session.capi_query_worker:977: endpoint __EDMC_WORKER_SHUTDOWN, exiting...
2024-06-23 11:49:04.119 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.close:121: Calling self.stop()
2024-06-23 11:49:04.120 UTC - INFO - 24992:18912:18912 companion.Session.capi_query_worker:1020: CAPI worker thread DONE
2024-06-23 11:49:04.120 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.stop:106: Stopping monitoring Dashboard
2024-06-23 11:49:04.122 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.stop:117: Done.
2024-06-23 11:49:04.123 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.close:135: Done.
2024-06-23 11:49:04.124 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1899: Closing journal monitor...
2024-06-23 11:49:04.125 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:324: Calling self.stop()...
2024-06-23 11:49:04.125 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.stop:288: Stopping monitoring Journal
2024-06-23 11:49:04.126 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.stop:320: Done.
2024-06-23 11:49:04.126 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:326: Done
2024-06-23 11:49:04.127 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:339: Done.
2024-06-23 11:49:04.127 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1903: Closing protocol handler...
2024-06-23 11:49:04.128 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1906: Closing Frontier CAPI sessions...
2024-06-23 11:49:04.129 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1910: Closing config...
2024-06-23 11:49:04.129 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1913: Destroying app window...
2024-06-23 11:49:04.197 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1916: Done.
Exception in thread Thread-3 (onexit):
Traceback (most recent call last):
2024-06-23 11:49:04.198 UTC - INFO - 24992:38316:38316 EDMarketConnector.__main__:2332: Exiting
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "EDMarketConnector.py", line 1866, in onexit
2024-06-23 11:49:04.200 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:205: No thread
  File "tkinter\__init__.pyc", line 2119, in wm_geometry
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
2024-06-23 11:49:04.200 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:207: Done.

%temp%\EDMarketConnector\EDMarketConnector-debug.log:
2024-06-23 11:48:55.725 UTC - INFO - 24992:38316:38316 EDMarketConnector.__main__:205: Setting TRACE level debugging due to either --trace or a --trace-on
2024-06-23 11:48:55.777 UTC - TRACE - 24992:38316:38316 EDMCLogging.__main__:90: Truncating plain logfile
2024-06-23 11:48:55.795 UTC - DEBUG - 24992:38316:38316 companion.Session.__init__:644: Starting CAPI queries thread...
2024-06-23 11:48:55.800 UTC - DEBUG - 24992:18912:18912 companion.Session.capi_query_worker:781: CAPI worker thread starting
2024-06-23 11:48:55.800 UTC - DEBUG - 24992:38316:38316 companion.Session.__init__:651: Done
2024-06-23 11:48:55.817 UTC - INFO - 24992:38316:38316 EDMarketConnector.__main__:2079: Startup v5.11.2+87f59a5 : Running on Python v3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)]
2024-06-23 11:48:55.821 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.__main__:2080: Platform: win32 sys.getwindowsversion(major=10, minor=0, build=22631, platform=2, service_pack='')
argv[0]: EDMarketConnector.exe
exec_prefix: C:\Program Files (x86)\EDMarketConnector
executable: C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe
sys.path: ['C:\\Program Files (x86)\\EDMarketConnector\\library.zip']
2024-06-23 11:48:55.822 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: Initial Locale
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.822 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: After LC_ALL defaults set
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.823 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.__main__:2120: Locale LC_CTYPE: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.837 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.log_locale:1977: Locale: After switching to UTF-8 encoding (same language)
Locale LC_COLLATE: ('de_DE', 'UTF-8')
Locale LC_CTYPE: ('de_DE', 'UTF-8')
Locale LC_MONETARY: ('de_DE', 'UTF-8')
Locale LC_NUMERIC: ('de_DE', 'UTF-8')
Locale LC_TIME: ('de_DE', 'UTF-8')
2024-06-23 11:48:55.838 UTC - DEBUG - 24992:38316:38316 EDMarketConnector.setup_killswitches:1988: fetching killswitches...
2024-06-23 11:48:55.839 UTC - INFO - 24992:38316:38316 killswitch.fetch_kill_switches:346: Attempting to fetch kill switches
2024-06-23 11:48:55.895 UTC - INFO - 24992:38316:38316 killswitch.parse_kill_switches:419: Kill switches last updated 18 October 2021
2024-06-23 11:48:55.896 UTC - TRACE - 24992:38316:38316 EDMCLogging.setup_main_list:90: 0 Active Killswitches:
2024-06-23 11:48:55.952 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "coriolis" from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
2024-06-23 11:48:55.957 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "eddn" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
2024-06-23 11:48:55.973 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "edsm" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
2024-06-23 11:48:55.981 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_start3:231: Starting worker thread...
2024-06-23 11:48:55.982 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:828: Starting...
2024-06-23 11:48:55.982 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_start3:235: Done.
2024-06-23 11:48:55.985 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2024-06-23 11:48:55.986 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2024-06-23 11:48:55.997 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_start3:206: Starting worker thread...
2024-06-23 11:48:55.999 UTC - DEBUG - 24992:39508:39508 plugins.inara.new_worker:1538: Starting...
2024-06-23 11:48:55.999 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_start3:210: Done.
2024-06-23 11:48:55.999 UTC - INFO - 24992:38316:38316 plug.Plugin.__init__:65: loading plugin "spansh_core" from "C:\Program Files (x86)\EDMarketConnector\plugins\spansh_core.py"
2024-06-23 11:48:56.016 UTC - INFO - 24992:38316:38316 plugins.eddn.EDDNSender.sqlite_queue_v1:211: New 'eddn_queue-v1.db' created
2024-06-23 11:48:56.093 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.start:198: Begin...
2024-06-23 11:48:56.175 UTC - DEBUG - 24992:24496:24496 plugins.edsm.process_discarded_events:749: Got "events to discard" list, commencing queue consumption...
2024-06-23 11:49:00.767 UTC - ERROR - 24992:38316:38316 monitor.EDLogs.start:224: Failed to find latest logfile
Traceback (most recent call last):
  File "monitor.pyc", line 221, in start
  File "monitor.pyc", line 282, in journal_newest_filename
  File "<frozen genericpath>", line 65, in getctime
OSError: [WinError 4350] This file is currently not available for use on this computer: '\\\\HOSTNAME\\Users$\\USERNAME\\Saved Games\\Frontier Developments\\Elite Dangerous\\Journal.2022-09-09T182727.01.log'
2024-06-23 11:49:00.822 UTC - INFO - 24992:38316:38316 update.check_for_fdev_updates:71: FDEV ID file commodity.csv already up to date.
2024-06-23 11:49:00.874 UTC - INFO - 24992:38316:38316 update.check_for_fdev_updates:71: FDEV ID file rare_commodity.csv already up to date.
2024-06-23 11:49:04.104 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1873: Starting shutdown procedures...
2024-06-23 11:49:04.105 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1876: Closing update checker...
2024-06-23 11:49:04.106 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1883: Notifying plugins to stop...
2024-06-23 11:49:04.107 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "EDDN" to stop...
2024-06-23 11:49:04.107 UTC - DEBUG - 24992:38316:38316 plugins.eddn.plugin_stop:2248: Calling this.eddn.close()
2024-06-23 11:49:04.108 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDN.close:605: Closing Sender...
2024-06-23 11:49:04.108 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:243: Closing db cursor.
2024-06-23 11:49:04.109 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:247: Closing db connection.
2024-06-23 11:49:04.109 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDNSender.close:251: Closing EDDN requests.Session.
2024-06-23 11:49:04.110 UTC - DEBUG - 24992:38316:38316 plugins.eddn.EDDN.close:609: Done.
2024-06-23 11:49:04.110 UTC - DEBUG - 24992:38316:38316 plugins.eddn.plugin_stop:2250: Done.
2024-06-23 11:49:04.110 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "EDSM" to stop...
2024-06-23 11:49:04.111 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_stop:260: Signalling queue to close...
2024-06-23 11:49:04.111 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:848: Empty queue message, setting closing = True
2024-06-23 11:49:04.112 UTC - DEBUG - 24992:24496:24496 plugins.edsm.worker:966: closing, so returning.
2024-06-23 11:49:04.113 UTC - DEBUG - 24992:38316:38316 plugins.edsm.plugin_stop:269: Done.
2024-06-23 11:49:04.113 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "Inara" to stop...
2024-06-23 11:49:04.114 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_stop:226: We have no way to ask new_worker to stop, but...
2024-06-23 11:49:04.114 UTC - DEBUG - 24992:38316:38316 plugins.inara.plugin_stop:233: Done.
2024-06-23 11:49:04.114 UTC - INFO - 24992:38316:38316 plug.notify_stop:263: Asking plugin "Spansh" to stop...
2024-06-23 11:49:04.115 UTC - INFO - 24992:38316:38316 plug.notify_stop:269: Done
2024-06-23 11:49:04.115 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1888: Unregistering hotkey manager...
2024-06-23 11:49:04.116 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:205: No thread
2024-06-23 11:49:04.116 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:207: Done.
2024-06-23 11:49:04.117 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1892: Closing CAPI query thread...
2024-06-23 11:49:04.118 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1896: Closing dashboard...
2024-06-23 11:49:04.119 UTC - INFO - 24992:18912:18912 companion.Session.capi_query_worker:977: endpoint __EDMC_WORKER_SHUTDOWN, exiting...
2024-06-23 11:49:04.119 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.close:121: Calling self.stop()
2024-06-23 11:49:04.120 UTC - INFO - 24992:18912:18912 companion.Session.capi_query_worker:1020: CAPI worker thread DONE
2024-06-23 11:49:04.120 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.stop:106: Stopping monitoring Dashboard
2024-06-23 11:49:04.122 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.stop:117: Done.
2024-06-23 11:49:04.123 UTC - DEBUG - 24992:38316:38316 dashboard.Dashboard.close:135: Done.
2024-06-23 11:49:04.124 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1899: Closing journal monitor...
2024-06-23 11:49:04.125 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:324: Calling self.stop()...
2024-06-23 11:49:04.125 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.stop:288: Stopping monitoring Journal
2024-06-23 11:49:04.126 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.stop:320: Done.
2024-06-23 11:49:04.126 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:326: Done
2024-06-23 11:49:04.127 UTC - DEBUG - 24992:38316:38316 monitor.EDLogs.close:339: Done.
2024-06-23 11:49:04.127 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1903: Closing protocol handler...
2024-06-23 11:49:04.128 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1906: Closing Frontier CAPI sessions...
2024-06-23 11:49:04.129 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1910: Closing config...
2024-06-23 11:49:04.129 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1913: Destroying app window...
2024-06-23 11:49:04.197 UTC - INFO - 24992:38316:38316 EDMarketConnector.AppWindow.onexit:1916: Done.
2024-06-23 11:49:04.198 UTC - INFO - 24992:38316:38316 EDMarketConnector.__main__:2332: Exiting
2024-06-23 11:49:04.200 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:205: No thread
2024-06-23 11:49:04.200 UTC - DEBUG - 24992:38316:38316 windows.WindowsHotkeyMgr.unregister:207: Done.

**Comment by chennin** [comment]
> I think the most relevant line in the debug log ist "OSError: [WinError 4350] This file is currently not available for use on this computer: '\\HOSTNAME\Users$\USERNAME\Saved Games\Frontier Developments\Elite Dangerous\Journal.2022-09-09T182727.01.log'"
> The journal file location is correct, EDMC is obviously finding the current game log file and I have no issues with running EDDiscovery.

What do you mean by "current"? That says 2022, did you miss a "not" or do you have other evidence for what EDMC is finding?

**Comment by Athanasius** [comment]
Indeed, it might be that EDDiscovery isn't even trying to read that old of a Journal file, and thus isn't encountering the same issue.  Is that 2022 file the actual latest file in the directory ?  What happens if you try to access that same file with a text editor ?

**Comment by kadiron** [comment]
Sorry, that's been misleading. I've meant it's able to find the correct journal dir. The file name in the log is an existent file name inside my journal dir, even though not the most current.

**Comment by Eahlstan** [comment]
> Indeed, it might be that EDDiscovery isn't even trying to read that old of a Journal file, and thus isn't encountering the same issue. Is that 2022 file the actual latest file in the directory ? What happens if you try to access that same file with a text editor ?

oO

EDDiscovery reads every journal file in the specified folder (or the default location if none specified), no matter how old it is.

**Comment by Athanasius** [comment]
The file being that old means it's not going to be held open by the game either (not that this should cause an issue).

Are we 100% certain that EDD and EDMC are being run as the same user ?  No wrapper script/bat file that's using runas ?

Any signs of an Anti-Virus or software Firewall deciding to get in EDMC's way, but not EDD's ?

**Comment by kadiron** [comment]
What happens if you try to access that same file with a text editor ?

I should have tried that myself before. Looks like this is an OS bug: Opening the file in powershell gives an file not found error, in CMD (after mapping the path to a drive letter) I'm getting "This file is currently not available for use on this computer." and accessing locally on the server it's perfectly readable. All with the same domain user.
Sorry for the hassle but seeing this, this must be an issue with Windows (Server) and not with EDMC.
Strange that this is the only situation where I'm facing this, though. Maybe that's because I've collected >2700 files in that directory. Don't know what EDDiscovery makes out of this, maybe it's just ignoring inaccessible files?
Anyways, thanks for your very quick responses!

**Comment by Rixxan** [comment]
Glad that the issue has been identified! Good luck in fixing it!

Will be closing this as a not EDMC issue, but if there's anything we can do to assist let us know.
