### ISSUE TITLE
Stuck on "Awaiting Full CMDR Login", running through WINE on macOS

### ISSUE THREAD

**Issue by bvsveera** [EDCD/EDMarketConnector#2300]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: 5.12.0+cc6e200
 - Game Version: Odyssey
 - OS: macOS Sequoia 15.0 [WINE bottle is configured as Windows 11 build version 22000]
 - OS Locale: English_Australia
 - If applicable: Browser - Safari

**Describe the bug**

After updating to the latest version of EDMC (5.12.0+cc6e200), the program is no longer working as before. All fields in the window are blank and the message at the bottom states "Awaiting Full CMDR Login". For context, I have just opened EDMC soon after launching Elite Dangerous and logging into Open play (in previous versions of EDMC, it only picks up game updates when launched *after* the game has been launched, not before). Clicking update leads to the message changing to 'Fetching data...' for a few minutes, after which it will state that authentication was successful, yet none of the fields have updated.

This issue appears to be similar to two other (now closed) issues. However, the action that fixed the program for them - running the .bat file - has not worked for me.

https://github.com/EDCD/EDMarketConnector/issues/2295
https://github.com/EDCD/EDMarketConnector/issues/2296

Uninstalling and downgrading to the last release of EDMC results in the program working as expected.

I understanding that running EDMC through WINE translation is quite the edge case, but it was working *perfectly* before the most recent update, and hopefully we can get it back to working perfectly once again.

**To Reproduce**
1. Launch Elite Dangerous
2. Launch EDMC (all fields are empty)
3. Click update
4. Wait for the successful authentication message

**Expected behavior**

Soon after launching EDMC, all of the fields should be populated, denoting CMDR name, ship, current system, etc.

**Screenshots**

Screenshots are attached.

**Additional context**

Running the game and EDMC through WINE translation on macOS Sequoia via Whisky. Release 5.11.3 was working as expected. My suspicion was raised after seeing the blank fields following the update. I thought nothing of it, until I travelled about 1000 Ly from the bubble, and noticed on Inara that it still listed my location as being at Ix (i.e. within the bubble). Downgrading back to 5.11.3 fixed it, but I'd like to see this fixed, if possible, in the event that future changes to the game/EDMC/EDDN etc. make this version incompatible.

As mentioned before, this appears to be similar to two previously opened issues, but their remedial steps did not work for me, and it appears they were running EDMC on Windows, hence why I'm opening this issue.

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [☑️] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [☑️ ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

Log files are attached.
<img width="176" alt="Screenshot 2024-09-27 at 4 35 54 pm" src="https://github.com/user-attachments/assets/8a00017b-d793-4db0-bcb7-07dfcd124d32">
<img width="176" alt="Screenshot 2024-09-27 at 4 40 53 pm" src="https://github.com/user-attachments/assets/ce9fffed-4dac-4993-9c1b-65869735df30">
<img width="380" alt="Screenshot 2024-09-27 at 4 41 26 pm" src="https://github.com/user-attachments/assets/3cdf2a3d-549c-4e29-a258-dd78da72120f">
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17160426/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/user-attachments/files/17160428/EDMarketConnector.log)

**Comment by Rixxan** [comment]
Looks like this was due to the way ctypes are working on WINE. 

```2024-09-27 06:35:40.552 UTC - ERROR - 2472:1044:1044 prefs.prefs:210: win32 and not is_wine, but ctypes.windll.user32.CalculatePopupWindowPosition invalid
Traceback (most recent call last):
  File "prefs.pyc", line 205, in <module>
  File "ctypes\__init__.pyc", line 389, in __getattr__
  File "ctypes\__init__.pyc", line 394, in __getitem__
AttributeError: function 'CalculatePopupWindowPosition' not found```

Will need to see what we have there and how we can fix it.

**Comment by bvsveera** [comment]
Ran a quick test with update 5.12.1, same problem appears to be present

**Comment by Rixxan** [comment]
Haven't had a chance to look at the ctypes code yet so this doesn't surprise me. My goal is to have this one in 5.12.2.

**Comment by Bjohnson131** [comment]
I'm seeing the same issue:

```
$ uname -a
Linux desktop 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

[EDMarketConnector-debug.log](https://github.com/user-attachments/files/18160061/EDMarketConnector-debug.log)

**Comment by TheNetos** [comment]
Same problem when running under Crossover v24.0.6 (24.0.6.37103).

Logs contain the error described above and another error related to multithreading.

[EDMarketConnector.log](https://github.com/user-attachments/files/18551651/EDMarketConnector.log)

**Comment by a0s** [comment]
Same issue for me. Any chance to fix?

**Comment by Rixxan** [comment]
> Same issue for me. Any chance to fix?
> 
> UPD With new CrossOver version Version 25.0 (25.0.0.38553) the error disappered.

I unfortunately have not had time nor the requisite system using WINE to check this out... but I hope you're right. My knowledge of the lower-level C is rudimentary at best. 

@Bjohnson131 @TheNetos @bvsveera, any of you able to confirm? Maybe this was a WINE thing?

**Comment by TheNetos** [comment]
This is exactly a problem with the Wine environment.

Let me check it out right now.

**Comment by TheNetos** [comment]
Yep, wine 10 works wonders.

Checked on version `5.12.4+b777c7b`.
CrossOver `25.0.0.38553`.

<img width="548" alt="Image" src="https://github.com/user-attachments/assets/6035d4d7-043b-4c43-b881-ee304663efbf" />

**Comment by Rixxan** [comment]
... PRAISE THE OMNISSIAH! I have no idea what changed or why it works now. I'll keep this on monitoring for a bit longer, but if everyone reports in or nobody reports it broken still, we'll call it good :)

**Comment by bvsveera** [comment]
> > Same issue for me. Any chance to fix?
> > UPD With new CrossOver version Version 25.0 (25.0.0.38553) the error disappered.
> 
> I unfortunately have not had time nor the requisite system using WINE to check this out... but I hope you're right. My knowledge of the lower-level C is rudimentary at best.
> 
> [@Bjohnson131](https://github.com/Bjohnson131) [@TheNetos](https://github.com/TheNetos) [@bvsveera](https://github.com/bvsveera), any of you able to confirm? Maybe this was a WINE thing?

I can also confirm that it's working in CrossOver 25 and Wine 10. I also agree that this bug probably had something to do with the older Wine 7.x environment that Whisky uses. Version 5.11.3 was working just fine for my purposes, but I'm glad to be back on the latest release of EDMC. Thanks for all the input everyone!
