### ISSUE TITLE
Issues with switching to different commanders

### ISSUE THREAD

**Issue by mearmortal** [EDCD/EDMarketConnector#2330]
**Please complete the following information:**

[//]: #
 
EDMC Version: 
 - 5.12.1+fc00839

OS Details:
- Operating System: Windows 10
- Version: 10.0.22631
- Machine: AMD64
- Python Version: 3.11.9

Environment Details
- Detected Locale: English_United Kingdom
- Detected Encoding: utf8
- Journal Directory: C:\Users\welsh\Saved Games\Frontier Developments\Elite Dangerous
- Game Version: 4.0.0.1900
- Game Build: r307202/r0 
- Using Odyssey: True
- Journal Dir Lockable: True

**Issue with switching to different accounts while the EDMC is running**

[//]: # It does appear that EDMC is loosing the ability to change accounts sometimes.  

**To Reproduce**
1. Launch EDMC, Launch Frontier version of Game, 1st commander, PG & Ship recognised.
2. Shutdown the game, can't have two instances of the game running on the same PC at the same time.
3. Launch the EPIC version of game, 2nd Commander, PG, & ship recognised. During launch of game, 1st commander etc, is blanked out until the new commander is fully running in the game. This is how I believe it's supposed to work.
4. Shutdown the game.
5. Launch the Steam version of the game, 2nd commander still visible along with PG & Ship name. Didn't blank out during launch of game this time. Stayed with 2nd commander.
6. Shutdown the game.
7. Launch another 4th commander from the EPIC version of the game, 2nd commander still visible along with PG & Ship name. Didn't blank out during launch of game this time. Stayed with 2nd commander.

Expected EDMC to blank out the 2nd and 3rd commander on launch of new instance of the game and load in the new commander details following fully loaded game, as per 1st and 2nd commander instances.

If I need to run through it a different way, say frontier, Steam, Epic, Epic next time, or Epic, Steam, Frontier, Epic let me know.

Not sure if it's a bug or not, but the behaviour seem to be ok for the 2nd instance, so can't explain why it doesn't work for the 3rd, or subsequent new instances loaded in.

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [ Yes] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [Yes ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
I believe the testing started around 2024-11-13 13:06:53.384 in the logs file
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17735706/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/user-attachments/files/17735707/EDMarketConnector.log)

4 Journal files for each cmdr.
[Journal.2024-11-13T132751.01.log](https://github.com/user-attachments/files/17735712/Journal.2024-11-13T132751.01.log)
[Journal.2024-11-13T132425.01.log](https://github.com/user-attachments/files/17735713/Journal.2024-11-13T132425.01.log)
[Journal.2024-11-13T131916.01.log](https://github.com/user-attachments/files/17735714/Journal.2024-11-13T131916.01.log)
[Journal.2024-11-13T130723.01.log](https://github.com/user-attachments/files/17735715/Journal.2024-11-13T130723.01.log)

**Comment by Athanasius** [comment]
This likely isn't helping:

```python
2024-11-13 13:19:16.723 UTC - INFO - 31052:26304:26304 monitor.EDLogs.worker:455: New Journal File. Was "C:\Users\welsh\Saved Games\Frontier Developments\Elite Dangerous\Journal.2024-11-13T130723.01.log", now "C:\Users\welsh\Saved Games\Frontier Developments\Elite Dangerous\Journal.2024-11-13T131916.01.log"
2024-11-13 13:20:08.330 UTC - INFO - 31052:28772:28772 EDMarketConnector.AppWindow.journal_event:1498: StartUp or LoadGame event
2024-11-13 13:20:08.332 UTC - INFO - 31052:28772:28772 dashboard.Dashboard.start:93: Monitoring Dashboard "C:\Users\welsh\Saved Games\Frontier Developments\Elite Dangerous"
EDMCOverlay: Overlay server is not running..
EDMCOverlay: EDMCOverlay is starting C:\Users\welsh\AppData\Local\EDMarketConnector\plugins\EDMCOverlay\EDMCOverlay.exe
DEBUG:EDMarketConnector.EDMC-Canonn-7.5.1:Refreshing News
DEBUG:EDMarketConnector.EDMC-Canonn-7.5.1:Refreshing News
Exception in thread Journal worker:
Traceback (most recent call last):
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "monitor.pyc", line 478, in worker
  File "monitor.pyc", line 2154, in game_running
TypeError: NoSuchProcess.__init__() missing 1 required positional argument: 'pid'```
If the journal monitoring thread is falling over then that would explain not picking up on a commander switch.

**Comment by Athanasius** [comment]
Change https://github.com/EDCD/EDMarketConnector/blob/Release/5.12.1/monitor.py#L2154 so that it's:

```python
raise psutil.NoSuchProcess(p.pid)
```

**Comment by Rixxan** [comment]
Good spot, the psutils [docs](https://psutil.readthedocs.io/en/latest/index.html#psutil.NoSuchProcess) do indicate this is required, I just happen to be blind.
