### ISSUE TITLE
[python3] - Need to find a better code-placement for plugin warning popup

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#522]
Using tk.messagebox() for a popup around EDMarketConnector.py:819 causes a thread-related error:

```
Traceback (most recent call last):
  File "C:\Users\Athan\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Athan\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 273, in worker
    self.root.event_generate('<<JournalEvent>>', when="tail")
  File "C:\Users\Athan\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1673, in event_generate
    self.tk.call(args)
RuntimeError: main thread is not in main loop```
So the code was moved to plug.py:202.  However this then causes the popup before the main window is correctly rendered (position and theme).  Find some other point at which to perform this check and trigger the popup.

1. It does need to be ASAP after the application starts running.  We don't want to trigger it after a user has had time to get in-game.
1. Ensure it's not causing any errors at all, such as the thread-related one above.

**Comment by Athanasius** [comment]
Tested good to me
