### ISSUE TITLE
Fleet Carriers appear to change lastStation.modules to be a list

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#671]
**To Reproduce**
1. Dock at fleet carrier, see stacktrace in log:
```
2020-08-21 13:06:28.140 - DEBUG - plugins.eddn.cmdr_data:726: Failed exporting data
Traceback (most recent call last):
  File "/home/ad/development/python/EDMarketConnector/plugins/eddn.py", line 716, in cmdr_data
    this.eddn.export_shipyard(data, is_beta)
  File "/home/ad/development/python/EDMarketConnector/plugins/eddn.py", line 312, in export_shipyard
    horizons: bool = is_horizons(
  File "/home/ad/development/python/EDMarketConnector/plugins/eddn.py", line 736, in is_horizons
    any(module.get('sku') == HORIZ_SKU for module in modules.values()) or
AttributeError: 'list' object has no attribute 'values'
```

**Comment by Athanasius** [comment]
We definitely want to catch and log this at least, even if it's Frontier's fault.

**Comment by FJRMaverick** [comment]
Seems to happen always, when docking at a station (fleet carrier), which has a market, but no commodity to sell or buy.

**Comment by Athanasius** [comment]
It's related to the station/FC not having *modules* for sale (the code that's tripping up is literally trying to iterate over the available modules).

**Comment by Athanasius** [comment]
Should be fixed in https://github.com/EDCD/EDMarketConnector/pull/701 - pending review.
