### ISSUE TITLE
Exception: socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by chr7** [EDCD/EDMarketConnector#677]
**Describe the bug**
EDMarketConnector 4.0.4 throws exception: "socket.timeout: The read operation timed out".
The exception is thrown in the background, so the app continues running.

**Traceback**
```
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 379, in query
    r = self.session.get(self.server + endpoint, timeout=timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 379, in query
    r = self.session.get(self.server + endpoint, timeout=timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "EDMarketConnector.py", line 444, in getandsend
    data = companion.session.station()
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 433, in station
    data = self.query(URL_QUERY)
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 385, in query
    raise ServerError('unable to get endpoint {}'.format(endpoint)) from e
companion.ServerError: unable to get endpoint /profile
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 379, in query
    r = self.session.get(self.server + endpoint, timeout=timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 379, in query
    r = self.session.get(self.server + endpoint, timeout=timeout)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/share/virtualenvs/EDMarketConnector-4.git-TzDn3H_C/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='companion.orerve.net', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "EDMarketConnector.py", line 444, in getandsend
    data = companion.session.station()
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 433, in station
    data = self.query(URL_QUERY)
  File "~/Programs/EDMarketConnector-4.git/companion.py", line 385, in query
    raise ServerError('unable to get endpoint {}'.format(endpoint)) from e
companion.ServerError: unable to get endpoint /profile
```

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04.5 LTS
 - Version 4.0.4

**Additional context**
* Active plugins:

1. EDSM-RSE 1.3.1
2. HabZone 1.20
3. LandingPad 1.2

* Data is sent to EDDN and Inara.
* Python 3.8.0
* pip list:
```
Package          Version
---------------- ---------
certifi          2019.9.11
chardet          3.0.4
idna             2.10
pathtools        0.1.2
pip              20.2.2
requests         2.24.0
semantic-version 2.8.5
setuptools       49.6.0
urllib3          1.25.10
watchdog         0.10.3
wheel            0.35.1
```

**Comment by Athanasius** [comment]
I think this is relatively harmless.  As you say the app continues running (something should be catching the `raise ServerError` in order to report back to the user).  The rest of the stack trace splat could be useful for *other* causes of such.  In this case we can tell it was just companion.orerve.net not responding in time, rather than an actual issue in the code.

**Comment by A-UNDERSCORE-D** [comment]
This still occurring?

**Comment by chr7** [comment]
I'm using version 4.2.3 in the meantime and couldn't notice it again.
