### ISSUE TITLE
Logging throws an exception if the caller is a name-mangled method

### ISSUE THREAD

**Issue by sersorrel** [EDCD/EDMarketConnector#764]
**Please complete the following information:**
 - Version: 4.1.3 or so, `commit f3e8dbf7c1239c334dfff5bb74240e219776c258 (HEAD -> refs/heads/stable, refs/remotes/origin/stable, refs/remotes/origin/main, refs/remotes/origin/HEAD)`
 - OS: Linux Ubuntu 18.04
 - OS Locale: en_GB.UTF-8

**Describe the bug**
If you call e.g. `logger.info` from within a function with a mangled name (a class method starting with two underscores and ending with zero or one underscores, e.g. `__server`), EDMC's logging infrastructure tries to look up the function on the class and fails:

```pytb
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ash/.local/share/EDMarketConnector/plugins/edmcoverlay/_edmcoverlay.py", line 94, in __server
    logger.info("edmcoverlay2: server running")
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1523, in handle
    if (not self.disabled) and self.filter(record):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/home/ash/src/EDMarketConnector/EDMCLogging.py", line 255, in filter
    (class_name, qualname, module_name) = self.caller_attributes(module_name=getattr(record, 'module'))
  File "/home/ash/src/EDMarketConnector/EDMCLogging.py", line 294, in caller_attributes
    fn = getattr(frame_class, frame_info.function)
AttributeError: 'Overlay' object has no attribute '__server'
```

**To Reproduce**
1. Install [edmcoverlay2](https://github.com/sersorrel/edmcoverlay2)
2. Run EDMC

**Expected behavior**
EDMC should support logging from class methods with mangled names.

**Comment by A-UNDERSCORE-D** [comment]
Sorry about that mess. I made a mess in git that I made worse by trying to fix. That PR should fix the issue.

**Comment by A-UNDERSCORE-D** [comment]
@sersorrel Should be fixed on develop now.

**Comment by Athanasius** [comment]
It's also now in stable.  @sersorrel do you need this in released versions ASAP, or can we wait maybe a week to see if any other bugfixes are made ?

**Comment by sersorrel** [comment]
I'm fine waiting for the next release :)

**Comment by Athanasius** [comment]
This should be fixed in the just-released 4.1.5

**Comment by Athanasius** [comment]
We merged @sersorrel 's fix into https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.6-rc2 so please re-test with that and report back.

**Comment by sersorrel** [comment]
I did in fact test before submitting the PR ;) but yes, `Release/4.1.6-rc2` works fine.
