### ISSUE TITLE
EDMC Failed to load Cmdr/System/Station on startup. AttributeError: 'EDLogs' object has no attribute 'systempopulation'

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDCD/EDMarketConnector#936]
**Please complete the following information:**
 - Version 4.2.4
 - OS: Windows 10
 - OS Locale: English
   
```
Exception in thread Journal worker:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "monitor.pyc", line 273, in worker
AttributeError: 'EDLogs' object has no attribute 'systempopulation'
```

**Describe the bug**
The application started up but did not display cmdr or location information nor did it send Location events to the plugin.
After shutting down and restarting it appears to behave normally. 

The current location was Kyloagh TE-M c22-46

**To Reproduce**

Unable to reproduce

**Expected behavior**
Normal startup

**Comment by NoFoolLikeOne** [comment]
Its possible that the game hadn't finished loading before I started EDMC I'll see if I can reproduce it

**Comment by NoFoolLikeOne** [comment]
Not been able to reproduce it so far. Must be a race condition .
