### ISSUE TITLE
CAPI: Odyssey shipyard list is different in some manner.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#986]
```
2021-04-08 15:23:38.366 - DEBUG - 8964:6940:6940 plugins.eddn.cmdr_data:939: Failed exporting data
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plugins\eddn.py", line 929, in cmdr_data
    this.eddn.export_shipyard(data, is_beta)
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plugins\eddn.py", line 428, in export_shipyard
    shipyard: List[Mapping[str, Any]] = sorted(
TypeError: '<' not supported between instances of 'dict' and 'str'
```

This is probably due to the `sorted()` there.

**Comment by Athanasius** [comment]
Fixed in #987
