### ISSUE TITLE
[Odyssey] - Weird "Docked" events

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#992]
These are probably to do with docking/landing your own ship at a surface settlement and/or getting back in it.

```
2021-04-09 22:06:43.469 - DEBUG - 1760:3916:3916 monitor.EDLogs.parse_entry:1026: Invalid journal entry:
b'{ "timestamp":"2021-04-09T21:06:43Z", "event":"Docked", "StationName":"", "StationType":"SurfaceStation", "DistFromStarLS":1739.402747 }\r\n'
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 647, in parse_entry
    elif self.system != entry['StarSystem']:
KeyError: 'StarSystem'

2021-04-09 23:03:41.790 - DEBUG - 1760:3916:3916 monitor.EDLogs.parse_entry:1026: Invalid journal entry:
b'{ "timestamp":"2021-04-09T22:02:38Z", "event":"Docked", "StationName":"", "StationType":"SurfaceStation", "DistFromStarLS":1736.624174 }\r\n'
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 647, in parse_entry
    elif self.system != entry['StarSystem']:
KeyError: 'StarSystem'

2021-04-09 23:28:52.955 - DEBUG - 1760:3916:3916 monitor.EDLogs.parse_entry:1026: Invalid journal entry:
b'{ "timestamp":"2021-04-09T22:27:43Z", "event":"Docked", "StationName":"", "StationType":"SurfaceStation", "DistFromStarLS":1736.632212 }\r\n'
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\monitor.py", line 647, in parse_entry
    elif self.system != entry['StarSystem']:
KeyError: 'StarSystem'
```

**Comment by Athanasius** [comment]
Indeed, I have:

```json
{
  "timestamp": "2021-04-09T21:06:07Z",
  "event": "ReceiveText",
  "From": "Boumal Synthetics Installation",
  "Message": "$STATION_docking_granted;",
  "Message_Localised": "Docking request granted.",
  "Channel": "npc"
}
{
  "timestamp": "2021-04-09T21:06:07Z",
  "event": "DockingGranted",
  "LandingPad": 1,
  "MarketID": 3805747200,
  "StationName": "",
  "StationType": "SurfaceStation"
}```
just before that first one.  This could well be due to the bug in Alpha Ph2/Hotfix 2 where you get a 'Scarlet Krait' error if you dock/land your own ship at a settlement with a Conflict Zone.

**Comment by Athanasius** [comment]
Re-check after Odyssey launch.

**Comment by Athanasius** [comment]
I've not seen this since Odyssey Alpha Phase 2, so will close this now.
